### ISSUE TITLE
Maths functions other than decimal no longer work?

### ISSUE THREAD

**Issue by zmike808** [cman8396/GECalc#2]
Maths functions other than decimal no longer work?
I'd be glad to try to do a PR seeing if i can find the issue and fix this. Assuming project dev is still active at least.

**Comment by cman8396** [comment]
Feel free to do a PR for this, I'm not in a position to update the plugin myself so this would be much appreciated.

**Comment by cman8396** [comment]
Fixed and tested, PR created for update to plugin-hub
