### ISSUE TITLE
Disables enter on interfaces after Varlmore part 2 update

### ISSUE THREAD

**Issue by daltonpearson** [cman8396/GECalc#3]
Quantity interfaces (GE value, withdraw x, etc) don't respond to Enter key strokes when this plugin is enabled following the varlamore part 2 update

**Comment by pogof** [comment]
Just figured it out too. Great plugin, please fix.

**Comment by cman8396** [comment]
I've replicated the issue and found where the problem is, however I haven't used Java since 2022 so it might take some time.

It seems to be an issue acros the board, as I've also verified that the same issue occurs with other plugins that modify the chatbox quantity.

**I'll continue looking at a fix and update accordingly.**

`2024-09-25 21:53:38 BST [AWT-EventQueue-0] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.AssertionError: must be called on client thread
	at client.setVarcStrValue(client.java:48726)
	at com.gecalc.GECalcPlugin.parseQuantity(GECalcPlugin.java:178)
	at com.gecalc.GECalcPlugin.keyPressed(GECalcPlugin.java:199)
	at net.runelite.client.input.KeyManager.processKeyPressed(KeyManager.java:89)
	at net.runelite.client.callback.Hooks.keyPressed(Hooks.java:350)
	at ak.keyPressed(ak.java:27144)
	at java.desktop/java.awt.Component.processKeyEvent(Component.java:6593)
	at java.desktop/java.awt.Component.processEvent(Component.java:6412)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1950)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:870)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1139)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1009)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:835)`

**Comment by cman8396** [comment]
Disabled plugin in RuneLite plugin-hub.
Best to disable due to multiple reports on github and RuneLite discord of the plugin interfering with all quantity input fields.

**Comment by rmaes4** [comment]
> I've replicated the issue and found where the problem is, however I haven't used Java since 2022 so it might take some time.
> 
> It seems to be an issue acros the board, as I've also verified that the same issue occurs with other plugins that modify the chatbox quantity.
> 
> **I'll continue looking at a fix and update accordingly.**
> 
> `2024-09-25 21:53:38 BST [AWT-EventQueue-0] ERROR net.runelite.client.RuneLite - Uncaught exception: java.lang.AssertionError: must be called on client thread at client.setVarcStrValue(client.java:48726) at com.gecalc.GECalcPlugin.parseQuantity(GECalcPlugin.java:178) at com.gecalc.GECalcPlugin.keyPressed(GECalcPlugin.java:199) at net.runelite.client.input.KeyManager.processKeyPressed(KeyManager.java:89) at net.runelite.client.callback.Hooks.keyPressed(Hooks.java:350) at ak.keyPressed(ak.java:27144) at java.desktop/java.awt.Component.processKeyEvent(Component.java:6593) at java.desktop/java.awt.Component.processEvent(Component.java:6412) at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011) at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843) at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1950) at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:870) at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1139) at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1009) at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:835)`

Decimal prices dev here. Just woke up to an issue created on my repository. Haven’t had a chance to investigate yet. Just wondering if you were able to find anything. Perhaps we can tackle this together.

**Comment by cman8396** [comment]
> Decimal prices dev here. Just woke up to an issue created on my repository. Haven’t had a chance to investigate yet. Just wondering if you were able to find anything. Perhaps we can tackle this together.

Morning rmaes4. 
Tried a few things but the same error occurs no matter what I do, but that might just be my lack of Java experiece in the last few years :)
I didn't try asking in the RuleLite discord if anyone knows but that might be a good next step. However I won't be able to investegate properly for a few days.

**Comment by rmaes4** [comment]
> > Decimal prices dev here. Just woke up to an issue created on my repository. Haven’t had a chance to investigate yet. Just wondering if you were able to find anything. Perhaps we can tackle this together.
> 
> Morning rmaes4. Tried a few things but the same error occurs no matter what I do, but that might just be my lack of Java experiece in the last few years :) I didn't try asking in the RuleLite discord if anyone knows but that might be a good next step. However I won't be able to investegate properly for a few days.

Good news, I was able to solve the issue. Anywhere you are using "setVarcStrValue", you now have to explicitly run that on the client thread. Should be an easy fix for you. See my changes here: https://github.com/rmaes4/decimal-prices/compare/1db835ba25debba83d310868e3ea49ba8cb24733...rmaes4:d5cf0945dad76954299f8b31e6bd4ceda2787df0

**Comment by cman8396** [comment]
> Good news, I was able to solve the issue. Anywhere you are using "setVarcStrValue", you now have to explicitly run that on the client thread. Should be an easy fix for you. See my changes here: [rmaes4/decimal-prices@1db835b...rmaes4:d5cf0945dad76954299f8b31e6bd4ceda2787df0](https://github.com/rmaes4/decimal-prices/compare/1db835ba25debba83d310868e3ea49ba8cb24733...rmaes4:d5cf0945dad76954299f8b31e6bd4ceda2787df0)

Thanks for letting me know, that's a massive help!
I took the opportunity to make some updates too, thanks again :)
